<!DOCTYPE html>
<html lang="bn">
<head>
    <meta charset="UTF-8">
    <title>Product Sales Summary Report ({{ $sdate }} to {{ $edate }})</title>
    <style>
        @page {
            margin: 15px;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #000000;
            font-size: 11px;
            margin: 0;
            padding: 10px;
        }
        .print-container {
            width: 100%;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #000000;
            padding-bottom: 10px;
            margin-bottom: 12px;
        }
        .company-title {
            font-size: 20px;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 3px;
        }
        .company-info {
            font-size: 10px;
            line-height: 1.3;
        }
        .report-title-badge {
            display: inline-block;
            border: 1.5px solid #000000;
            padding: 4px 12px;
            font-size: 11px;
            font-weight: bold;
            margin-top: 8px;
            text-transform: uppercase;
            background-color: #f8fafc;
        }
        .meta-table {
            width: 100%;
            margin-bottom: 12px;
            border-collapse: collapse;
        }
        .meta-table td {
            padding: 6px 10px;
            border: 1px solid #000000;
            font-size: 10px;
        }
        .stats-table {
            width: 100%;
            margin-bottom: 15px;
            border-collapse: collapse;
        }
        .stats-table td {
            width: 33.33%;
            padding: 8px;
            border: 1.5px solid #000000;
            text-align: center;
        }
        .stat-val {
            font-size: 14px;
            font-weight: bold;
        }
        .stat-lbl {
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            margin-top: 2px;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        .data-table th, .data-table td {
            padding: 6px 8px;
            border: 1px solid #000000;
            text-align: left;
            font-size: 10px;
        }
        .data-table th {
            background-color: #f1f5f9;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9px;
        }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-bold { font-weight: bold; }

        .signatures {
            margin-top: 40px;
            width: 100%;
        }
        .sig-block {
            width: 40%;
            float: left;
            text-align: center;
        }
        .sig-block-right {
            width: 40%;
            float: right;
            text-align: center;
        }
        .sig-line {
            border-top: 1.5px solid #000000;
            margin-bottom: 4px;
        }
        .sig-title {
            font-size: 10px;
            font-weight: bold;
        }
        .clear {
            clear: both;
        }
    </style>
</head>
<body>

    @php
        $comPhone = get_setting('com_phone') ?: get_setting('phone') ?: '01888714428';
        $companyName = empty(get_setting('com_name')) ? (get_setting('site_title') ?: 'Lotus Bloem') : get_setting('com_name');
        $startDateStr = \Carbon\Carbon::parse($sdate)->format('d M, Y');
        $endDateStr = \Carbon\Carbon::parse($edate)->format('d M, Y');
    @endphp

    <div class="print-container">
        <!-- Header -->
        <div class="header">
            <div class="company-title">{{ $companyName }}</div>
            <div class="company-info">
                {{ empty(get_setting('com_address')) ? 'Dhaka, Bangladesh' : get_setting('com_address') }}
                @if($comPhone)
                    | Phone: {{ $comPhone }}
                @endif
                @if(get_setting('com_email'))
                    | Email: {{ get_setting('com_email') }}
                @endif
            </div>

            <div class="report-title-badge">{{ $isSalesman ? 'PRODUCT SALES SUMMARY REPORT' : 'PRODUCT SALES & PROFIT SUMMARY REPORT' }}</div>
        </div>

        <!-- Meta Info Table -->
        <table class="meta-table">
            <tr>
                <td><span>Date Range:</span> <strong>{{ $startDateStr }} to {{ $endDateStr }}</strong></td>
                <td><span>Branch:</span> <strong>{{ $branch->name ?? 'Main Branch' }}</strong></td>
            </tr>
            <tr>
                <td><span>Print Time:</span> <strong>{{ date('d M, Y h:i A') }}</strong></td>
                <td><span>Generated By:</span> <strong>{{ $authUser->name ?? auth()->user()->name }} ({{ $authUser->role->name ?? auth()->user()->role->name ?? 'User' }})</strong></td>
            </tr>
            <tr>
                <td colspan="2"><span>Total Item Types Sold:</span> <strong>{{ count($summary) }} Items</strong></td>
            </tr>
        </table>

        <!-- Stats Table -->
        <table class="stats-table">
            <tr>
                <td style="width: {{ $isSalesman ? '25%' : '20%' }};">
                    <div class="stat-val">{{ number_format($grandTotalQty, 2) }}</div>
                    <div class="stat-lbl">Total Sold Qty</div>
                </td>
                <td style="width: {{ $isSalesman ? '25%' : '20%' }};">
                    <div class="stat-val">Tk {{ number_format($grandTotalSaleAmount, 2) }}</div>
                    <div class="stat-lbl">Gross Sale</div>
                </td>
                <td style="width: {{ $isSalesman ? '25%' : '20%' }};">
                    <div class="stat-val">Tk {{ number_format($grandTotalReturnAmount ?? 0, 2) }}</div>
                    <div class="stat-lbl">Return Amount</div>
                </td>
                <td style="width: {{ $isSalesman ? '25%' : '20%' }}; background-color: #f8fafc;">
                    <div class="stat-val" style="color: #000;">Tk {{ number_format($grandTotalNetSale ?? ($grandTotalSaleAmount - ($grandTotalReturnAmount ?? 0) - ($grandTotalDiscount ?? 0)), 2) }}</div>
                    <div class="stat-lbl" style="font-weight: bold; color: #000;">Net Sale Amount</div>
                </td>
                <td style="width: {{ $isSalesman ? '25%' : '20%' }};">
                    <div class="stat-val">Tk {{ number_format($grandTotalDiscount ?? 0, 2) }}</div>
                    <div class="stat-lbl">Total Discount</div>
                </td>
            </tr>
            @if(!$isSalesman)
            <tr>
                <td colspan="5" style="padding: 6px; background-color: #f1f5f9; text-align: center;">
                    <span style="font-size: 11px; font-weight: bold;">Total Net Profit: Tk {{ number_format($grandTotalProfit, 2) }}</span>
                </td>
            </tr>
            @endif
        </table>

        <!-- Data Table -->
        <table class="data-table">
            <thead>
                <tr>
                    <th style="width: 25px;" class="text-center">#</th>
                    <th>Product Name & Code</th>
                    <th class="text-center">Sold Qty</th>
                    <th class="text-right">Total Sale</th>
                    <th class="text-center">Return Qty</th>
                    <th class="text-right">Return Amount</th>
                    <th class="text-right">Discount</th>
                    @if(!$isSalesman)
                    <th class="text-right">Total Cost</th>
                    <th class="text-right">Total Profit</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @forelse($summary as $key => $item)
                <tr>
                    <td class="text-center text-bold">{{ $key + 1 }}</td>
                    <td>
                        <div class="text-bold">{{ $item['name'] }}</div>
                        <div style="font-size: 8px; color: #444;">Code: {{ $item['code'] }}</div>
                    </td>
                    <td class="text-center text-bold">{{ number_format($item['total_qty'], 2) }}</td>
                    <td class="text-right text-bold">Tk {{ number_format($item['total_sale'], 2) }}</td>
                    <td class="text-center text-bold">{{ number_format($item['return_qty'], 2) }}</td>
                    <td class="text-right text-bold">Tk {{ number_format($item['return_amount'], 2) }}</td>
                    <td class="text-right text-bold">Tk {{ number_format($item['discount'] ?? 0, 2) }}</td>
                    @if(!$isSalesman)
                    <td class="text-right text-bold">Tk {{ number_format($item['total_cost'], 2) }}</td>
                    <td class="text-right text-bold">Tk {{ number_format($item['total_profit'], 2) }}</td>
                    @endif
                </tr>
                @empty
                <tr>
                    <td colspan="{{ $isSalesman ? '7' : '9' }}" class="text-center" style="padding: 15px;">No sales found in selected date range.</td>
                </tr>
                @endforelse
            </tbody>
            @if(count($summary) > 0)
            <tfoot>
                <tr style="font-weight: bold; background-color: #f1f5f9;">
                    <td colspan="2" class="text-right">Grand Total:</td>
                    <td class="text-center">{{ number_format($grandTotalQty, 2) }}</td>
                    <td class="text-right">Tk {{ number_format($grandTotalSaleAmount, 2) }}</td>
                    <td class="text-center">{{ number_format($grandTotalReturnQty, 2) }}</td>
                    <td class="text-right">Tk {{ number_format($grandTotalReturnAmount, 2) }}</td>
                    <td class="text-right">Tk {{ number_format($grandTotalProductDiscount ?? 0, 2) }}</td>
                    @if(!$isSalesman)
                    <td class="text-right">Tk {{ number_format($grandTotalCostAmount, 2) }}</td>
                    <td class="text-right">Tk {{ number_format($grandTotalProfit, 2) }}</td>
                    @endif
                </tr>
                <tr style="font-weight: bold; background-color: #e2e8f0;">
                    <td colspan="{{ $isSalesman ? '7' : '9' }}" class="text-center" style="padding: 6px;">
                        Net Sale Amount (Gross Sale - Return - Discount): Tk {{ number_format($grandTotalNetSale ?? ($grandTotalSaleAmount - ($grandTotalReturnAmount ?? 0) - ($grandTotalDiscount ?? 0)), 2) }}
                    </td>
                </tr>
            </tfoot>
            @endif
        </table>

        <!-- Signatures -->
        <div class="signatures">
            <div class="sig-block">
                <div class="sig-line"></div>
                <div class="sig-title">Prepared By</div>
            </div>
            <div class="sig-block-right">
                <div class="sig-line"></div>
                <div class="sig-title">Manager / Admin Signature</div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

</body>
</html>
